Issue number:1622 Reviewed by:kanduls,veiming
git-svn-id: https://svn.java.net/svn/opensso~svn/trunk@2791 b2119f5d-607e-cfcf-c5d3-9fa3ed8061d4

diff --git a/products/amserver/scripts/tune/unix/amtune-prepareDSTuner b/products/amserver/scripts/tune/unix/amtune-prepareDSTuner
--- a/products/amserver/scripts/tune/unix/amtune-prepareDSTuner
+++ b/products/amserver/scripts/tune/unix/amtune-prepareDSTuner
@@ -1,5 +1,5 @@
 #!/bin/sh
-#
+
 # The contents of this file are subject to the terms
 # of the Common Development and Distribution License
 # (the License). You may not use this file except in
@@ -19,117 +19,113 @@
 # your own identifying information:
 # "Portions Copyrighted [year] [name of copyright owner]"
 #
-# $Id: amtune-prepareDSTuner,v 1.1 2007-02-23 23:41:26 bt199000 Exp $
+# $Id: amtune-prepareDSTuner,v 1.2 2008-02-14 02:19:24 ykwon Exp $
 #
-# Copyright 2007 Sun Microsystems Inc. All Rights Reserved
+# Copyright 2008 Sun Microsystems Inc. All Rights Reserved
 #
-########################################################################
+
 getListDefaultAMIndexes() {
 
-    index_ldif_file=$IS_CONFIG_DIR/ldif/index.ldif
-    if [ ! -f "$index_ldif_file" ]; then
-        index_ldif_file=$IS_CONFIG_DIR/index.ldif
+        index_ldif_file=$IS_CONFIG_DIR/ldif/index.ldif
         if [ ! -f "$index_ldif_file" ]; then
-            $ECHO
-            exit 1
-	fi
-    fi
+           index_ldif_file=$IS_CONFIG_DIR/index.ldif
+           if [ ! -f "$index_ldif_file" ]; then
+              $ECHO
+              exit 1
+           fi
+        fi
 
-    $ECHO `$GREP "dn: " $index_ldif_file | $AWK -F" " '{ print $2 }' | $AWK -F"," '{ print $1 }' | $AWK -F"=" '{ print $2 }'`
+        $ECHO `$GREP "dn: " $index_ldif_file | $AWK -F" " '{ print $2 }' | $AWK -F"," '{ print $1 }' | $AWK -F"=" '{ print $2 }'`
 }
 
 prepareDirectoryTuner() {
-    $ECHO `gettext "Preparing Directory Server Tuner..."`
+    if [ "$OSTYPE" = "HP-UX" ]; then
+            gettext=/usr/local/bin/gettext
+    else
+        gettext=/bin/gettext
+    fi
+    $ECHO `$gettext "Preparing Directory Server Tuner..."`
     $ECHO $LINE_SEP
-    $ECHO `gettext "Determining Current Settings..."`
-
-    ROOT_SUFFIX=`getConfigEntry "com.iplanet.am.rootsuffix"`
-    DS_INSTANCE_DIR=`getInstanceDir`
+    $ECHO `$gettext "Determining Current Settings..."`
 
     ###############ACI############################
-    #NormalizeDNandReplaceComma "$ROOT_SUFFIX" "_"
-    #
-    #if [ "$OSTYPE" = "Linux" ]; then
-    #    replaceCharacter "$NMDN" "&" "\\\&"
-    #else
-    #    replaceCharacter "$NMDN" "&" "\&"
-    #fi
-    #NM_SUFFIX=$NEWSTR
-    ##############################################
+    NormalizeDNandReplaceComma "$ROOT_SUFFIX" "_"
+    
+    if [ "$OSTYPE" = "Linux" ]; then
+        replaceCharacter "$NMDN" "&" "\\\&"
+    else
+        replaceCharacter "$NMDN" "&" "\&"
+    fi
+    NM_SUFFIX=$NEWSTR
 
     tmp_file=/tmp/amtune-directory
     ds_tar_file=$DS_TAR_DIR/amtune-directory.tar
 
     if [ -f $ds_tar_file ]; then
-        $RM $ds_tar_file
+       $RM $ds_tar_file
     fi
 
-    $ECHO `gettext "Creating Directory Server Tuner tar file: $ds_tar_file"`
+    $ECHO `$gettext "Creating Directory Server Tuner tar file: "` "$ds_tar_file"
 
-    ds_version=`getDSVersion`
     list_default_am_indexes=`getListDefaultAMIndexes`
     if [ "$list_default_am_indexes" = "" ]; then
-	$ECHO "WARNING: Cann't find Access Manager Index file  $IS_CONFIG_DIR/ldif/index.ldif.  Use default list."
-	list_default_am_indexes="nsRoleDN memberof iplanet-am-static-group-dn iplanet-am-modifiable-by iplanet-am-user-federation-info-key sunxmlkeyvalue o ou sunPreferredDomain associatedDomain sunOrganizationAlias"
+        $ECHO `$gettext "WARNING: Can't find Federated Access Manager Index file.  Using the default list in amtune-directory.template."`
     fi
 
     $CP $AMTUNE_UTILS_SCRIPT /tmp/amtune-utils
     $CP $SCRIPT_LOCATION/amtune-directory.template $tmp_file
 
-    replace_line $tmp_file "DS_HOST="                   "DS_HOST='$DS_HOST'"
-    replace_line $tmp_file "DS_PORT="                   "DS_PORT='$DS_PORT'"
-    replace_line $tmp_file "ROOT_SUFFIX="               "ROOT_SUFFIX='$ROOT_SUFFIX'"
-    replace_line $tmp_file "DIRMGR_UID="                "DIRMGR_UID='$DIRMGR_UID'"
-    replace_line $tmp_file "RAM_DISK="                  "RAM_DISK='$RAM_DISK'"
-    replace_line $tmp_file "DS_INSTANCE_DIR="           "DS_INSTANCE_DIR='$DS_INSTANCE_DIR'"
-    replace_line $tmp_file "OSTYPE="           		"OSTYPE='$OSTYPE'"
-    replace_line $tmp_file "DS_VERSION="          	"DS_VERSION='$ds_version'"
-    replace_line $tmp_file "list_am_default_index="     "    list_am_default_index='$list_default_am_indexes'"
-
-    ################################ACI###################################################
-    #replace_line $tmp_file "ENABLE_MODE="               "ENABLE_MODE='$ENABLE_MODE'"
-    #replace_line $tmp_file "NM_SUFFIX="                 "NM_SUFFIX='$NM_SUFFIX'"
-    #replace_line $tmp_file "ORG_OBJECT_CLASS="          "ORG_OBJECT_CLASS='$ORG_OBJECT_CLASS'"
-    ######################################################################################
+    ###########################################ACI#######################################################
+    NormalizeDNandReplaceComma "$ROOT_SUFFIX" "_"
+    ###########################################ACI#######################################################
 
     chmod +x $tmp_file
-    #################################ACI#################################################################
-    #$TAR cvf $ds_tar_file -C /tmp amtune-directory -C /tmp amtune-utils -C $SCRIPT_LOCATION remacis.ldif
-    #####################################################################################################
 
-    $TAR cvf $ds_tar_file -C /tmp amtune-directory -C /tmp amtune-utils
+    $TAR cvf $ds_tar_file remacis.ldif amtune-samplepasswordfile -C /tmp amtune-directory -C /tmp amtune-utils
 
     $RM $tmp_file
 
     $ECHO 
-    $ECHO `gettext "Directory Server Tuner tar file: $ds_tar_file"`
-    $ECHO `gettext "Steps to tune directory server:"`
-    $ECHO `gettext "1.  Copy the DS Tuner tar to the DS System"`
-    $ECHO `gettext "2.  Untar the DS Tuner in a temporary location"`
-    $ECHO `gettext "3.  Execute the following script in 'REVIEW' mode : amtune-directory"`
-    $ECHO `gettext "4.  Review carefully the recommended tunings for DS"`
-    $ECHO `gettext "5.  If you are sure of applying these changes to DS, modify the following lines in amtune-directory"`
-    $ECHO `gettext "	a.  AMTUNE_MODE="`
-    $ECHO `gettext "	These parameters can also be modified or left unchange to use default values"`
-    $ECHO `gettext "	b.  AMTUNE_LOG_LEVEL="`
-    $ECHO `gettext "	c.  AMTUNE_DEBUG_FILE_PREFIX="`
-    $ECHO `gettext "	d.  DB_BACKUP_DIR_PREFIX="`
-    if [ `$ECHO $ds_version | $CUT -c1` -le 5 ]; then
-        $ECHO `gettext "Its highly recommended to run db2bak before running amtune-directory"`
-    else
-        $ECHO `gettext "Its highly recommended to run dsadm backup before running amtune-directory"`
-    fi
+    $ECHO `$gettext "Directory Server Tuner tar file: $ds_tar_file"`
+    $ECHO `$gettext "Steps to tune directory server:"`
+    $ECHO `$gettext "1.  Copy the DS Tuner tar to the DS System"`
+    $ECHO `$gettext "2.  Untar the DS Tuner in a temporary location"`
+    $ECHO `$gettext "3.  Execute the following script in 'REVIEW' mode : amtune-directory"`
+    $ECHO `$gettext "4.  Review carefully the recommended tunings for DS"`
+    $ECHO `$gettext "5.  If you are sure of applying these changes to DS, modify the following lines in amtune-directory"`
+    $ECHO `$gettext "    or in amtune-directory.template before running this script."`
+    $ECHO `$gettext "   a.  "` "AMTUNE_MODE="
+    $ECHO `$gettext "   These parameters can also be modified or left unchanged to use default values"`
+    $ECHO `$gettext "   b.  "` "AMTUNE_LOG_LEVEL="
+    $ECHO `$gettext "   c.  "` "AMTUNE_DEBUG_FILE_PREFIX="
+    $ECHO `$gettext "   d.  "` "DB_BACKUP_DIR_PREFIX="
+    $ECHO `$gettext "   e.  "` "DS_HOST="
+    $ECHO `$gettext "   f.  "` "DS_PORT="
+    $ECHO `$gettext "   g.  "` "ROOT_SUFFIX="
+    $ECHO `$gettext "   h.  "` "DIRMGR_UID="
+    $ECHO `$gettext "   i.  "` "DS_INSTANCE_DIR="
+    $ECHO `$gettext "   j.  "` "DS_VERSION="
+    $ECHO `$gettext "   k.  "` "ENABLE_MODE="
+    $ECHO `$gettext "   l.  "` "NM_SUFFIX="
+    $ECHO `$gettext "   m.  "` "ORG_OBJECT_CLASS="
+    $ECHO `$gettext "It's highly recommended to run db2bak before running amtune-directory in case of Sun DS 5.x."`
+    $ECHO `$gettext "or dsadm backup before running amtune-directory in case of Sun DS 6.x."`
     $ECHO 
 }
 #############################################################################
 # Start of main program
 #############################################################################
-# This flag is used only when Access Manager is deployed as single
+# This flag is used only when Federated Access Manager is deployed as single
 # web-application.
 ##@SINGLEWAR_FLAG@
 
 SCRIPT_LOCATION=`dirname $0`
 AMTUNE_SCRIPT_RECORD_STRING="AMTUNE_DS_SCRIPT"
+TOOLS_HOME="@TOOLS_HOME@"
+TEXTDOMAIN=amtune-prepareDSTuner
+TEXTDOMAINDIR=$TOOLS_HOME/locale
+export TEXTDOMAIN
+export TEXTDOMAINDIR
 
 # import the environment
 if [ -f $SCRIPT_LOCATION/amtune-env ]; then
@@ -138,10 +134,12 @@ if [ -f $SCRIPT_LOCATION/amtune-env ]; then
     fi
 fi
 
-ECHO_MSG "Access Manager - Directory Server Tuner Preparation Script"
+ECHO_MSG "`$gettext 'Federated Access Manager - Directory Server Tuner Preparation Script'`"
 
 DS_TAR_DIR=$SCRIPT_LOCATION
 
-prepareDirectoryTuner	| eval $OUTPUT_TYPE
+prepareDirectoryTuner   | eval $OUTPUT_TYPE
+
+$RM $DSADMIN_PASSFILE
 
 ECHO_MSG $PARA_SEP 
